USE BANK_SYSTEM

DROP VIEW IF EXISTS DEPOSIT_VIEW;
CREATE VIEW DEPOSIT_VIEW 
AS
SELECT A.ACCOUNT_NO, A.ACCOUNT_TYPE, A.ACCOUNT_BALANCE, CONCAT(C.FIRST_NAME, " ", C.MIDDLE_NAME, " ", C.LAST_NAME) ACCOUNT_HOLDER
FROM ACCOUNT A, CUSTOMER C, CUSTOMER_ACCOUNT_RELATION CAR
WHERE A.ACCOUNT_NO=CAR.ACCOUNT_NO AND CAR.CUSTOMER_ID=C.CUSTOMER_ID;
