USE BANK_SYSTEM
DELIMITER //
DROP PROCEDURE IF EXISTS ADD_BRANCH;
CREATE PROCEDURE ADD_BRANCH
(
	IN P_BRANCH_CODE VARCHAR(20),
	IN P_IFSC_CODE VARCHAR(20),
	IN P_LOCATION VARCHAR(20),
	IN P_ADDRESS VARCHAR(255),
	IN P_TEL_NO VARCHAR(20),
	IN P_FAX_NO VARCHAR(20)							
)
BEGIN
	INSERT INTO BRANCH_LIST (BRANCH_CODE, IFSC_CODE, LOCATION, ADDRESS, TELEPHONE_NO, FAX_NO)
	VALUES (P_BRANCH_CODE, P_IFSC_CODE, P_LOCATION, P_ADDRESS, P_TEL_NO, P_FAX_NO);
END;
//
