USE BANK_SYSTEM
DELIMITER //

DROP PROCEDURE IF EXISTS ADD_EMPLOYEE;
CREATE PROCEDURE  ADD_EMPLOYEE (
IN P_FIRST_NAME VARCHAR(20),
IN P_MIDDLE_NAME VARCHAR(20),
IN P_LAST_NAME VARCHAR(20),
IN P_GENDER VARCHAR(20),
IN P_DATE_OF_BIRTH DATE,
IN P_ADDRESS TEXT,
IN P_CONTACT_NO VARCHAR(20),
IN P_E_MAIL VARCHAR(20),
IN P_EMERGENCY_CONTACT_NO VARCHAR(20),
IN P_HIGHEST_QUALIFICATION VARCHAR(20),
IN P_DESIGNATION VARCHAR(20),
IN P_DATE_OF_JOINING DATE,
IN P_DEPARTMENT_NO VARCHAR(20),
IN P_BRANCH_CODE VARCHAR(20),
OUT P_EMPLOYEE_ID VARCHAR(20)
)
BEGIN
SELECT COUNT(EMPLOYEE_ID) INTO P_EMPLOYEE_ID FROM EMPLOYEE;
SET P_EMPLOYEE_ID=P_EMPLOYEE_ID+1;
INSERT INTO EMPLOYEE
(
FIRST_NAME,
MIDDLE_NAME,
LAST_NAME,
GENDER,
DATE_OF_BIRTH,
ADDRESS ,
CONTACT_NO,
E_MAIL,
EMERGENCY_CONTACT_NO,
HIGHEST_QUALIFICATION,
DESIGNATION,
DATE_OF_JOINING,
DEPARTMENT_NO,
BRANCH_CODE
)
VALUES
(
P_FIRST_NAME,
P_MIDDLE_NAME,
P_LAST_NAME,
P_GENDER,
P_DATE_OF_BIRTH,
P_ADDRESS,
P_CONTACT_NO,
P_E_MAIL,
P_EMERGENCY_CONTACT_NO,
P_HIGHEST_QUALIFICATION,
P_DESIGNATION,
P_DATE_OF_JOINING,
P_DEPARTMENT_NO,
P_BRANCH_CODE
);
END;
//
