
USE BANK_SYSTEM
DELIMITER //
DROP PROCEDURE IF EXISTS ADD_ACCOUNT_NUMBER;
CREATE PROCEDURE ADD_ACCOUNT_NUMBER
(
	IN P_ACCOUNT_NO VARCHAR(20),
	IN P_ACCOUNT_TYPE VARCHAR(20),
	IN P_NET_BANKING VARCHAR(10),
	IN P_DEBIT_CARD VARCHAR(10),
	IN P_CREDIT_CARD VARCHAR(10),
	IN P_CHECK_BOOK VARCHAR(10)
)
BEGIN
	INSERT INTO ACCOUNT (ACCOUNT_NO, ACCOUNT_TYPE, NET_BANKING, DEBIT_CARD,	CREDIT_CARD, CHECK_BOOK)
	VALUES(P_ACCOUNT_NO, P_ACCOUNT_TYPE, P_NET_BANKING, P_DEBIT_CARD, P_CREDIT_CARD, P_CHECK_BOOK);
END;
//
