USE BANK_SYSTEM
DELIMITER //
DROP PROCEDURE IF EXISTS UPDATE_CONTACT;
CREATE PROCEDURE UPDATE_CONTACT
(
   IN P_EMPLOYEE_ID VARCHAR(20),
   IN P_CONTACT FLOAT(10) 
)
BEGIN
	UPDATE EMPLOYEE SET CONTACT_NO=P_CONTACT WHERE EMPLOYEE_ID=P_EMPLOYEE_ID; 
END;
//
