USE BANK_SYSTEM
DELIMITER //
DROP PROCEDURE IF EXISTS UPDATE_DESIGNATION;
CREATE PROCEDURE UPDATE_DESIGNATION
(
   IN P_EMPLOYEE_ID VARCHAR(20),
   IN P_JOB_NAME FLOAT(10) 
)
BEGIN
	UPDATE EMPLOYEE SET DESIGNATION=P_JOB_NAME WHERE EMPLOYEE_ID=P_EMPLOYEE_ID; 
END;
//
