USE BANK_SYSTEM
DELIMITER //
DROP PROCEDURE IF EXISTS UPDATE_DEPARTMENT;
CREATE PROCEDURE UPDATE_DEPARTMENT
(
   IN P_EMPLOYEE_ID VARCHAR(20),
   IN P_DEPARTMENT_NO FLOAT(10) 
)
BEGIN
	UPDATE EMPLOYEE SET DEPARTMENT_NO=P_DEPARTMENT_NO WHERE EMPLOYEE_ID=P_EMPLOYEE_ID; 
END;
//
